 # This file should contain everything to configure the workflow on a global scale.
host:
  storage.googleapis.com/gtex_analysis_v8/

annotations_file:
  annotations/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt

rnaseq_file:
   rna_seq_data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz
